Support `push --force` for non-ff changes

diff --git a/src/main/bash/push b/src/main/bash/push
--- a/src/main/bash/push
+++ b/src/main/bash/push
@@ -5,7 +5,7 @@ set -e
 set -u
 
 usage() {
-    echo "usage: push [--all-at-once | --dry-run | --if-needed | --no-fetch]... [<commit-ish>]"
+    echo "usage: push [--all-at-once | --dry-run | --force | --if-needed | --no-fetch]... [--] [<commit-ish>]"
 }
 
 show_help() {
@@ -21,9 +21,10 @@ so that you can keep on working while the build is running.
 
 The current branch is pushed by default, or you can specify the commit-ish (branch, commit, HEAD, …) to use.
 
-The first step is a check to make sure you have a fast-forward commit.
+The first step is a check to make sure you have a fast-forward commit,
+unless `--force` is used to push with the **potentially destructive** and unrecommended `--force` option on `git push`.
 To ensure we have the current remote state,
-this is preceeded by a call to `git fetch` unless disabled with the `--no-fetch` flag.
+the fast-forward check is preceeded by a call to `git fetch` unless disabled with the `--no-fetch` flag.
 
 Each commit is validated and pushed individually, or you can `push --all-at-once`.
 
@@ -45,6 +46,7 @@ EOF
 
 all_at_once=false
 dry_run=false
+force=false
 if_needed=false
 perform_fetch=true
 
@@ -52,6 +54,7 @@ while (( $# > 0 )); do
     case "$1" in
         --all-at-once) all_at_once=true;;
         --dry-run) dry_run=true;;
+        --force) force=true;;
         --if-needed) if_needed=true;;
         --no-fetch) perform_fetch=false;;
         -'?' | --help) show_help; exit 0;;
@@ -76,7 +79,7 @@ fi
 to_push="$(git rev-parse "${1-HEAD}")"
 echo "Last commit to push ${to_push}"
 
-if [ "${perform_fetch}" == true ]; then
+if [ "${force}" != true ] && [ "${perform_fetch}" = true ]; then
     git fetch
 fi
 
@@ -110,8 +113,12 @@ fi
 
 merge_base="$(git merge-base "${to_push}" "${upstream_commit}")"
 if [ "${merge_base}" != "${upstream_commit}" ]; then
-    echo "Error: merge-base is ${merge_base}, which is not the same as upstream ${upstream}. Please rebase." >&2
-    exit 1
+    if [ "${force}" = true ]; then
+        echo "WARNING (would be error, but --force specified): merge-base is ${merge_base}, which is not the same as upstream ${upstream}."
+    else
+        echo "Error: merge-base is ${merge_base}, which is not the same as upstream ${upstream}. Please rebase." >&2
+        exit 1
+    fi
 fi
 
 if [ "${all_at_once}" = false ]; then
