Massage the new tagrelease script
With input from Felix.

diff --git a/src/main/bash/tagrelease b/src/main/bash/tagrelease
--- a/src/main/bash/tagrelease
+++ b/src/main/bash/tagrelease
@@ -5,7 +5,7 @@ set -u
 set -o pipefail
 
 usage() {
-    echo "usage: tagrelease --version <version>"
+    echo "usage: tagrelease [--no-fetch] (--major | --minor | --patch | --version <version>) [[--] <commit>]"
 }
 
 show_help() {
@@ -17,24 +17,22 @@ with the version provided in the current repo. It brings up an editor for the
 message which is prepulated with the commit messages since the previous
 release.
 
-The format of version is not enforce, however it is recommended to follow the
+A release type can be specified with `--major`, `--minor` or `--patch`,
+in which case the version number will be calculated relative to the version of
+the previous tagged release.
+
+The format of version is not enforced, however it is recommended to follow the
 conventions of [semantic versioning][semver]. The tag name will be the version prefixed
-with the letter v.
+with the letter v, e.g. `tagrelease --version 1.2.34` creates a tag named `v1.2.34`.
+
+When the `--no-fetch` option is given
+
+The commit to be tagged can be passed as a argument and defaults to HEAD.
 
 [semver]: http://semver.org/
 
 EOF
 }
-
-while (( $# > 0 )); do
-    case "$1" in
-        --version) version="$2"; shift;;
-        -'?' | --help) show_help; exit 0;;
-        -*) { echo "Error: unexpected option $1"; usage; echo; echo "Use -? or --help for help, or -- to separate arguments from options"; } >&2; exit 2;;
-        *) break;;
-    esac
-    shift
-done
 
 function usage_error() {
     printf 'Error: %s\n' "$@"
@@ -42,39 +40,72 @@ function usage_error() {
     exit 2
 } >&2
 
+set_mode() {
+    [[ -z "${mode:-}" ]] || usage_error "multiple version specifiers"
+    mode="$1"
+}
 
-if [[ -z "${version:-}" ]]; then
-    usage_error 'Missing version. Version must be passed in with `--version <version>`'
+perform_fetch=true
+
+while (( $# > 0 )); do
+    case "$1" in
+        --major) set_mode 1;;
+        --minor) set_mode 2;;
+        --patch) set_mode 3;;
+        --version) set_mode 0; version="$2"; shift;;
+        --no-fetch) perform_fetch=false;;
+        -'?' | --help) show_help; exit 0;;
+        --) break;;
+        -*) { echo "Error: unexpected option $1"; usage; echo; echo "Use -? or --help for help, or -- to separate arguments from options"; } >&2; exit 2;;
+        *) break;;
+    esac
+    shift
+done
+
+case $# in
+    0) committish=HEAD;;
+    1) committish="$1";;
+    *) usage_error "unexpected arguments: ${*:2}"
+esac
+
+[[ -n "${mode:-}" ]] || usage_error "missing version specifier"
+
+commit="$(git rev-parse "${committish}^{commit}")"
+
+if [[ "${perform_fetch}" == true ]]; then
+    git fetch
 fi
 
-dirty=$(git status --porcelain)
-if [ "${dirty}" ]; then
-    usage_error "Cannot release because these files are dirty:
-${dirty}
-"
-    exit 1
-fi >&2
+if previous_release_tag="$(git describe --tags --match="v*" --abbrev=0 "${commit}" 2>/dev/null)"; then
+    previous_release_commit="$(git rev-parse "${previous_release_tag}^{commit}")"
+    echo ${previous_release_tag}
+    echo "${commit}" != "${previous_release_commit}"
+    [[ "${commit}" != "${previous_release_commit}" ]] || usage_error "no changes since previous commit: ${committish} and previous release tag ${previous_release_tag} both point to ${commit}"
+    log_range="${previous_release_tag}..${commit}"
+else
+    [[ "${mode}" -eq 0 ]] || usage_error "can't find previous release; consider using an explicit --version <version>"
+    log_range="${commit}"
+fi
 
-git pull --rebase
-
-find . -name target -prune -exec rm -r {} \;
-
+if [[ "${mode}" -ne 0 ]]; then
+    previous_release_version="${previous_release_tag#v}"
+    awk_program="$(printf 'BEGIN { FS="."; OFS="." } { if ($NF==1) if (%i!=1) $2=0; $%i+=1; print }' "${mode}" "${mode}")"
+    version="$(echo "${previous_release_version}" | awk "${awk_program}")"
+fi
 tag="v${version}"
 
-previous_release_tag=$( git describe --abbrev=0 || git describe --tags --abbrev=0 || git rev-list HEAD | tail -n 1 )
+release_notes_file="$(mktemp -t "${tag}-release-notes.XXXXXX")"
+git log --reverse "${log_range}" > "${release_notes_file}"
+vim "${release_notes_file}"
 
+git tag --force --file "${release_notes_file}" "${tag}" "${commit}"
 
-git log --pretty=format:"# %s
+rm "${release_notes_file}"
 
-%b
+cat <<EOF
+Release has been tagged as ${tag}
+To push the tag run:
 
-"  "${previous_release_tag}"..HEAD > /tmp/release-notes-candidate.txt
+    git push origin "${tag}" "release-${tag}:master"
 
-vim /tmp/release-notes-candidate.txt
-
-release_notes=$(cat /tmp/release-notes-candidate.txt)
-
-git tag -f "${tag}" --annotate --message "${release_notes}"
-
-echo "Release has been tagged to push run:"
-echo git push origin "${tag}" "release-${tag}:master"
+EOF
